
name: Build and Release fade-compendiums (Stable)

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.release.tag_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Substitute Manifest and Download URLs in the module.json
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: cschleiden/replace-tokens@v1
        with:
          files: 'module.json'
        env:
          VERSION: ${{ env.VERSION }}
          URL: https://github.com/${{ github.repository }}
          MANIFEST: https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/module.json
          DOWNLOAD: https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/module.zip
          CHANGELOG: https://github.com/${{ github.repository }}/releases/tag/${{ env.VERSION }}

      - name: Prepare release zip
        if: env.is_valid == 'true'
        run: |
          zip -r module.zip ./* -x '.git*' -x '.github/*' -x 'packsrc/*' -x 'node_modules/*' -x 'scripts/build/*' -x 'scripts/ps/*' -x 'package.json' -x 'package-lock.json' -x '.vscode/*'

      - name: Prepare release notes
        if: env.is_valid == 'true'
        id: prepare_notes
        env:
          RELEASE_BODY: ${{ github.event.release.body }}
        run: |
          {
            echo "## Pandora box artifacts collection "
            echo
            printf "%s\n" "$RELEASE_BODY"
            echo
            echo "This is a STABLE version of Pandora [hb]."
            echo "To install manually, use this URL:"
            echo "https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/module.json"
          } > release_notes.txt

      - name: Create GitHub release
        if: env.is_valid == 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }} (STABLE)"
          prerelease: false
          artifacts: './module.json, ./module.zip'
          bodyfile: release_notes.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          updateOnlyUnreleased: false
          makeLatest: true

      
